### PR TITLE
Fix `dyn` missing in wasm_bindgen.rs

### LINKED ISSUE #427: Not compiling with newest version of dependencies
After updating wasm-bindgen to 0.2.86 (I think) I get a compilation error when trying to compile with wasm
This was with `rustc 1.71.0-nightly (5ea3f0ae0 2023-05-23)` but fails on stable also
```
error[E0433]: failed to resolve: unresolved import
  --> src/webcore/ffi/wasm_bindgen.rs:67:32
   |
67 |             alloc: &Closure< Fn( usize ) -> *mut u8 >,
   |                                ^ unresolved import

error[E0425]: cannot find function `wasm_bindgen_initialize` in this scope
  --> src/webcore/ffi/wasm_bindgen.rs:77:22
   |
77 |         let module = wasm_bindgen_initialize( memory, table, &alloc, &free );
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

### PR DESCRIPTION
**Pull request by Dampfwalze**
Fixes https://github.com/koute/stdweb/issues/427

This is **IMPORTANT!!!** This crate does not compile otherwise!!!

### CODE REVIEW

**Comment by Dampfwalze** [comment]
@koute Please review ASAP.
